//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessiaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public int ID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<decimal> MinimalPrice { get; set; }
        public string Image { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> EmployeeCount { get; set; }
        public Nullable<int> WorkshopNumber { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
    }
}
